List<String> questions = [
  "How would you rate your overall satisfaction today?",
  "How do you feel about your current work-life balance?",
  "How would you rate the quality of your sleep last night?",
  "How satisfied are you with your current job?",
  "How do you feel about your physical health today?",
  "How would you rate your productivity today?",
  "How do you feel about the weather today?",
  "How satisfied are you with your social life?",
  "How do you feel about the amount of free time you have?",
  "How would you rate your stress level today?",
  "How satisfied are you with your diet today?",
  "How do you feel about your financial situation?",
  "How would you rate your energy level today?",
  "How do you feel about your personal relationships?",
  "How satisfied are you with your progress toward your goals?",
  "How do you feel about the level of support you receive from others?",
  "How would you rate your mental clarity today?",
  "How do you feel about your current living situation?",
  "How satisfied are you with your recent achievements?",
  "How do you feel about your current workload?",
  "How would you rate your creativity today?",
  "How do you feel about your ability to handle challenges?",
  "How satisfied are you with your recent purchases?",
  "How do you feel about the quality of your meals today?",
  "How would you rate your confidence level today?",
  "How do you feel about your current level of happiness?",
  "How satisfied are you with your recent decisions?",
  "How do you feel about your ability to manage time effectively?",
  "How would you rate your communication with others today?",
  "How do you feel about the level of motivation you have?",
  "How satisfied are you with your current routine?"
];

final List<String> keywords = [
  'stress',
  'anxiety',
  'depression',
  'loneliness',
  'panic attack',
  'therapy',
  'self-care',
  'sleep',
  'motivation',
  'relationship',
  'coping strategies',
  'meditation',
  'breathing exercises',
  'support groups',
  'mindfulness',
  'burnout',
  'anger',
  'grief',
  'isolation',
  'mental health',
  'self-esteem',
  'worry',
  'exercise',
  'diet',
  'work-life balance',
  'social anxiety',
  'fear',
  'overthinking',
  'life purpose',
  'happiness',
  'trauma',
  'addiction',
  'acceptance',
  'forgiveness',
  'resilience',
  'empathy',
  'hello',
  'hi',
  'how are you',
  'good morning',
  'good evening',
  'what’s up',
  'tell me a joke',
  'thank you',
  'goodbye',
  'bye',
  'what’s your name',
  'where are you from',
  'how old are you',
  'what’s your favorite color'
];

final List<String> responses = [
  'Stress can be overwhelming. Would you like some tips on how to manage it?',
  'Anxiety is tough, but you are not alone. Would you like to try a breathing exercise?',
  'Depression can be heavy. Remember, it’s okay to seek help. Would you like information on support?',
  'Loneliness can be difficult. Connecting with others might help. Can I suggest some ways to do that?',
  'Panic attacks are scary, but they are temporary. Let’s try to ground you. How about some calming techniques?',
  'Therapy is a great way to work through challenges. Would you like to know more about how it can help?',
  'Self-care is crucial. It’s important to take time for yourself. Would you like some self-care ideas?',
  'Sleep is essential for your well-being. Would you like some tips to improve your sleep?',
  'Staying motivated can be hard. Let’s talk about setting small, achievable goals. Ready to get started?',
  'Relationships can be challenging. Communication is key. Want to talk about some strategies?',
  'Coping strategies can make a big difference. Want to explore some that might work for you?',
  'Meditation can help calm your mind. Would you like to try a quick session?',
  'Breathing exercises can help reduce stress. Let’s do one together. Ready?',
  'Support groups provide a space to share and listen. Would you like information on finding one?',
  'Mindfulness can help you stay present. Would you like to practice a mindfulness exercise?',
  'Burnout is a sign that you need to rest. Let’s discuss how to regain your energy.',
  'Anger is a natural emotion, but it’s important to manage it. Want to try some calming techniques?',
  'Grief is a process. It’s okay to feel what you’re feeling. Would you like to talk about it?',
  'Isolation can intensify negative feelings. Let’s explore ways to stay connected.',
  'Mental health is important. I’m here to listen. How can I support you today?',
  'Self-esteem impacts how you feel about yourself. Let’s work on building your confidence.',
  'Worry can take over your thoughts. Let’s find ways to manage it.',
  'Exercise can boost your mood. Want some ideas for getting started?',
  'Diet plays a role in mental health. Would you like to talk about healthy eating habits?',
  'Work-life balance is key to well-being. Let’s discuss ways to achieve it.',
  'Social anxiety can make social situations difficult. Let’s explore strategies to help.',
  'Fear is a natural response, but it doesn’t have to control you. Let’s talk about managing it.',
  'Overthinking can be exhausting. Let’s try some techniques to quiet your mind.',
  'Finding purpose in life can be fulfilling. Let’s discuss what matters most to you.',
  'Happiness is something we all strive for. Let’s talk about what brings you joy.',
  'Trauma can leave lasting effects. It’s okay to seek help. Would you like to talk about it?',
  'Addiction is challenging, but recovery is possible. Would you like resources for support?',
  'Acceptance is a powerful tool. Let’s talk about accepting things we cannot change.',
  'Forgiveness can be freeing. Would you like to explore how to forgive?',
  'Resilience is about bouncing back from difficulties. Let’s work on building your resilience.',
  'Empathy helps us connect with others. Let’s discuss how to cultivate empathy in your life.',
  'Hello! How can I assist you today?',
  'Hi there! What can I do for you?',
  'I’m doing well, thank you! How about you?',
  'Good morning! I hope your day is off to a great start.',
  'Good evening! How was your day?',
  'Not much, just here to help. What’s up with you?',
  'Sure! Why don’t scientists trust atoms? Because they make up everything!',
  'You’re welcome! I’m always here to help.',
  'Goodbye! Take care and have a great day!',
  'Bye! Hope to chat with you again soon!',
  'I’m your friendly chatbot, here to assist with mental health and more.',
  'I’m from the digital world, here to support you wherever you are.',
  'Age doesn’t apply to me, but I’m wise beyond my (non-existent) years!',
  'I don’t have a favorite color, but I think all colors are beautiful!'
];
