List<String> questions = [
  "How would you rate your overall satisfaction today?",
  "How do you feel about your current work-life balance?",
  "How would you rate the quality of your sleep last night?",
  "How satisfied are you with your current job?",
  "How do you feel about your physical health today?",
  "How would you rate your productivity today?",
  "How do you feel about the weather today?",
  "How satisfied are you with your social life?",
  "How do you feel about the amount of free time you have?",
  "How would you rate your stress level today?",
  "How satisfied are you with your diet today?",
  "How do you feel about your financial situation?",
  "How would you rate your energy level today?",
  "How do you feel about your personal relationships?",
  "How satisfied are you with your progress toward your goals?",
  "How do you feel about the level of support you receive from others?",
  "How would you rate your mental clarity today?",
  "How do you feel about your current living situation?",
  "How satisfied are you with your recent achievements?",
  "How do you feel about your current workload?",
  "How would you rate your creativity today?",
  "How do you feel about your ability to handle challenges?",
  "How satisfied are you with your recent purchases?",
  "How do you feel about the quality of your meals today?",
  "How would you rate your confidence level today?",
  "How do you feel about your current level of happiness?",
  "How satisfied are you with your recent decisions?",
  "How do you feel about your ability to manage time effectively?",
  "How would you rate your communication with others today?",
  "How do you feel about the level of motivation you have?",
  "How satisfied are you with your current routine?"
];
